name: generate-docs
run-name: generate-docs
on:
    push:
        branches:
            - master
jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        
    steps:
        - uses: actions/checkout@v4
        - run: ./dtcw install doctoolchain
        - run: ./dtcw generateHTML
        - uses: stefanzweifel/git-auto-commit-action@v5
