name: generate-docs
on:
    push:
        branches:
            - main
jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        
    steps:
        - uses: actions/checkout@v4
        - run: ls -l
        - uses: stefanzweifel/git-auto-commit-action@v5
